<a href="https://colab.research.google.com/github/ChetanGoud77/PYTHON/blob/main/DAY_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [4]:
df=sns.load_dataset('taxis')
df

pickup             dropoff  passengers  distance  fare  \
0    2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.0   
1    2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0   
2    2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.5   
3    2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.0   
4    2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.0   
...                  ...                 ...         ...       ...   ...   
6428 2019-03-31 09:51:53 2019-03-31 09:55:27           1      0.75   4.5   
6429 2019-03-31 17:38:00 2019-03-31 18:34:23           1     18.74  58.0   
6430 2019-03-23 22:55:18 2019-03-23 23:14:25           1      4.14  16.0   
6431 2019-03-04 10:09:25 2019-03-04 10:14:29           1      1.12   6.0   
6432 2019-03-13 19:31:22 2019-03-13 19:48:02           1      3.85  15.0   

       tip  tolls  total   color      payment            pickup_zone  \
0     2.15    0.0  12.95  yellow  credit card        Lenox Hill West   
1     0.00    0.0   9.30  yellow         cash  Upper West Side South   
2     2.36    0.0  14.16  yellow  credit card          Alphabet City   
3     6.15    0.0  36.95  yellow  credit card              Hudson Sq   
4     1.10    0.0  13.40  yellow  credit card           Midtown East   
...    ...    ...    ...     ...          ...                    ...   
6428  1.06    0.0   6.36   green  credit card      East Harlem North   
6429  0.00    0.0  58.80   green  credit card                Jamaica   
6430  0.00    0.0  17.30   green         cash    Crown Heights North   
6431  0.00    0.0   6.80   green  credit card          East New York   
6432  3.36    0.0  20.16   green  credit card            Boerum Hill   

                          dropoff_zone pickup_borough dropoff_borough  
0                  UN/Turtle Bay South      Manhattan       Manhattan  
1                Upper West Side South      Manhattan       Manhattan  
2                         West Village      Manhattan       Manhattan  
3                       Yorkville West      Manhattan       Manhattan  
4                       Yorkville West      Manhattan       Manhattan  
...                                ...            ...             ...  
6428              Central Harlem North      Manhattan       Manhattan  
6429  East Concourse/Concourse Village         Queens           Bronx  
6430                    Bushwick North       Brooklyn        Brooklyn  
6431      East Flatbush/Remsen Village       Brooklyn        Brooklyn  
6432                   Windsor Terrace       Brooklyn        Brooklyn  

[6433 rows x 14 columns]

In [5]:
df.sample(5)

pickup             dropoff  passengers  distance  fare  \
5577 2019-03-28 08:47:57 2019-03-28 08:58:56           1      1.83   9.5   
582  2019-03-15 09:40:55 2019-03-15 10:07:14           1      1.86  16.0   
1667 2019-03-02 09:51:41 2019-03-02 09:52:52           1      0.51   3.5   
913  2019-03-23 11:26:58 2019-03-23 11:35:17           2      1.30   7.5   
3148 2019-03-20 18:00:57 2019-03-20 18:06:41           1      1.13   6.5   

       tip  tolls  total   color      payment            pickup_zone  \
5577  0.00    0.0  10.30   green         cash                Astoria   
582   1.25    0.0  20.55  yellow  credit card               Flatiron   
1667  1.36    0.0   8.16  yellow  credit card        Lenox Hill East   
913   0.00    0.0  10.80  yellow          NaN  Upper East Side South   
3148  0.00    0.0  10.80  yellow         cash  Upper West Side North   

             dropoff_zone pickup_borough dropoff_borough  
5577             Steinway         Queens          Queens  
582        Midtown Center      Manhattan       Manhattan  
1667      Lenox Hill West      Manhattan       Manhattan  
913   Lincoln Square West      Manhattan       Manhattan  
3148  Lincoln Square East      Manhattan       Manhattan

In [6]:
df.head(15)

pickup             dropoff  passengers  distance  fare   tip  \
0  2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.0  2.15   
1  2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0  0.00   
2  2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.5  2.36   
3  2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.0  6.15   
4  2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.0  1.10   
5  2019-03-11 10:37:23 2019-03-11 10:47:31           1      0.49   7.5  2.16   
6  2019-03-26 21:07:31 2019-03-26 21:17:29           1      3.65  13.0  2.00   
7  2019-03-22 12:47:13 2019-03-22 12:58:17           0      1.40   8.5  0.00   
8  2019-03-23 11:48:50 2019-03-23 12:06:14           1      3.63  15.0  1.00   
9  2019-03-08 16:18:37 2019-03-08 16:26:57           1      1.52   8.0  1.00   
10 2019-03-16 10:02:25 2019-03-16 10:22:29           1      3.90  17.0  0.00   
11 2019-03-20 19:39:42 2019-03-20 19:45:36           1      1.53   6.5  2.16   
12 2019-03-18 21:27:14 2019-03-18 21:34:16           1      1.05   6.5  1.00   
13 2019-03-19 07:55:25 2019-03-19 08:09:17           1      1.75  10.5  0.00   
14 2019-03-27 12:13:34 2019-03-27 12:25:48           0      2.90  11.5  0.00   

    tolls  total   color      payment                pickup_zone  \
0     0.0  12.95  yellow  credit card            Lenox Hill West   
1     0.0   9.30  yellow         cash      Upper West Side South   
2     0.0  14.16  yellow  credit card              Alphabet City   
3     0.0  36.95  yellow  credit card                  Hudson Sq   
4     0.0  13.40  yellow  credit card               Midtown East   
5     0.0  12.96  yellow  credit card  Times Sq/Theatre District   
6     0.0  18.80  yellow  credit card          Battery Park City   
7     0.0  11.80  yellow          NaN                Murray Hill   
8     0.0  19.30  yellow  credit card          East Harlem South   
9     0.0  13.30  yellow  credit card        Lincoln Square East   
10    0.0  17.80  yellow         cash          LaGuardia Airport   
11    0.0  12.96  yellow  credit card      Upper West Side South   
12    0.0  11.30  yellow  credit card                Murray Hill   
13    0.0  13.80  yellow         cash        Lincoln Square West   
14    0.0  14.80  yellow         cash   Financial District North   

                 dropoff_zone pickup_borough dropoff_borough  
0         UN/Turtle Bay South      Manhattan       Manhattan  
1       Upper West Side South      Manhattan       Manhattan  
2                West Village      Manhattan       Manhattan  
3              Yorkville West      Manhattan       Manhattan  
4              Yorkville West      Manhattan       Manhattan  
5                Midtown East      Manhattan       Manhattan  
6     Two Bridges/Seward Park      Manhattan       Manhattan  
7                    Flatiron      Manhattan       Manhattan  
8              Midtown Center      Manhattan       Manhattan  
9                Central Park      Manhattan       Manhattan  
10                    Astoria         Queens          Queens  
11           Manhattan Valley      Manhattan       Manhattan  
12             Midtown Center      Manhattan       Manhattan  
13  Times Sq/Theatre District      Manhattan       Manhattan  
14    Two Bridges/Seward Park      Manhattan       Manhattan

In [7]:
df.tail(8)

pickup             dropoff  passengers  distance   fare  \
6425 2019-03-07 15:34:30 2019-03-07 16:31:06           1      9.12  26.32   
6426 2019-03-28 08:04:47 2019-03-28 08:07:46           1      0.71   4.50   
6427 2019-03-23 18:26:09 2019-03-23 18:49:12           1      7.07  20.00   
6428 2019-03-31 09:51:53 2019-03-31 09:55:27           1      0.75   4.50   
6429 2019-03-31 17:38:00 2019-03-31 18:34:23           1     18.74  58.00   
6430 2019-03-23 22:55:18 2019-03-23 23:14:25           1      4.14  16.00   
6431 2019-03-04 10:09:25 2019-03-04 10:14:29           1      1.12   6.00   
6432 2019-03-13 19:31:22 2019-03-13 19:48:02           1      3.85  15.00   

       tip  tolls  total  color      payment          pickup_zone  \
6425  0.00    0.0  26.82  green  credit card           Park Slope   
6426  0.50    0.0   5.80  green  credit card         Central Park   
6427  0.00    0.0  20.00  green         cash          Parkchester   
6428  1.06    0.0   6.36  green  credit card    East Harlem North   
6429  0.00    0.0  58.80  green  credit card              Jamaica   
6430  0.00    0.0  17.30  green         cash  Crown Heights North   
6431  0.00    0.0   6.80  green  credit card        East New York   
6432  3.36    0.0  20.16  green  credit card          Boerum Hill   

                          dropoff_zone pickup_borough dropoff_borough  
6425                     East New York       Brooklyn        Brooklyn  
6426             Upper West Side North      Manhattan       Manhattan  
6427                 East Harlem South          Bronx       Manhattan  
6428              Central Harlem North      Manhattan       Manhattan  
6429  East Concourse/Concourse Village         Queens           Bronx  
6430                    Bushwick North       Brooklyn        Brooklyn  
6431      East Flatbush/Remsen Village       Brooklyn        Brooklyn  
6432                   Windsor Terrace       Brooklyn        Brooklyn

In [8]:
df['color'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...  
6428    False
6429    False
6430    False
6431    False
6432    False
Name: color, Length: 6433, dtype: bool

In [9]:
df['color'].isnull().sum()

0

In [10]:
df['payment'].isnull().sum()

44

In [11]:
df.isnull().sum()

pickup              0
dropoff             0
passengers          0
distance            0
fare                0
tip                 0
tolls               0
total               0
color               0
payment            44
pickup_zone        26
dropoff_zone       45
pickup_borough     26
dropoff_borough    45
dtype: int64

In [13]:
df.shape[0]

6433

In [14]:
(df.isnull().sum()/df.shape[0])*100

pickup             0.000000
dropoff            0.000000
passengers         0.000000
distance           0.000000
fare               0.000000
tip                0.000000
tolls              0.000000
total              0.000000
color              0.000000
payment            0.683973
pickup_zone        0.404166
dropoff_zone       0.699518
pickup_borough     0.404166
dropoff_borough    0.699518
dtype: float64

In [ ]:
missing data handling
1) Imputation
    1) stastical measures
    2) parameter

2) Delete data
    rows
    columns

In [16]:
df.drop('pickup_zone',axis=1)

pickup             dropoff  passengers  distance  fare  \
0    2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.0   
1    2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0   
2    2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.5   
3    2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.0   
4    2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.0   
...                  ...                 ...         ...       ...   ...   
6428 2019-03-31 09:51:53 2019-03-31 09:55:27           1      0.75   4.5   
6429 2019-03-31 17:38:00 2019-03-31 18:34:23           1     18.74  58.0   
6430 2019-03-23 22:55:18 2019-03-23 23:14:25           1      4.14  16.0   
6431 2019-03-04 10:09:25 2019-03-04 10:14:29           1      1.12   6.0   
6432 2019-03-13 19:31:22 2019-03-13 19:48:02           1      3.85  15.0   

       tip  tolls  total   color      payment  \
0     2.15    0.0  12.95  yellow  credit card   
1     0.00    0.0   9.30  yellow         cash   
2     2.36    0.0  14.16  yellow  credit card   
3     6.15    0.0  36.95  yellow  credit card   
4     1.10    0.0  13.40  yellow  credit card   
...    ...    ...    ...     ...          ...   
6428  1.06    0.0   6.36   green  credit card   
6429  0.00    0.0  58.80   green  credit card   
6430  0.00    0.0  17.30   green         cash   
6431  0.00    0.0   6.80   green  credit card   
6432  3.36    0.0  20.16   green  credit card   

                          dropoff_zone pickup_borough dropoff_borough  
0                  UN/Turtle Bay South      Manhattan       Manhattan  
1                Upper West Side South      Manhattan       Manhattan  
2                         West Village      Manhattan       Manhattan  
3                       Yorkville West      Manhattan       Manhattan  
4                       Yorkville West      Manhattan       Manhattan  
...                                ...            ...             ...  
6428              Central Harlem North      Manhattan       Manhattan  
6429  East Concourse/Concourse Village         Queens           Bronx  
6430                    Bushwick North       Brooklyn        Brooklyn  
6431      East Flatbush/Remsen Village       Brooklyn        Brooklyn  
6432                   Windsor Terrace       Brooklyn        Brooklyn  

[6433 rows x 13 columns]

In [19]:
df.drop(['pickup','color','payment','total'],axis=1,inplace=True)

In [20]:
df

dropoff  passengers  distance  fare   tip  tolls  \
0    2019-03-23 20:27:24           1      1.60   7.0  2.15    0.0   
1    2019-03-04 16:19:00           1      0.79   5.0  0.00    0.0   
2    2019-03-27 18:00:25           1      1.37   7.5  2.36    0.0   
3    2019-03-10 01:49:51           1      7.70  27.0  6.15    0.0   
4    2019-03-30 13:37:14           3      2.16   9.0  1.10    0.0   
...                  ...         ...       ...   ...   ...    ...   
6428 2019-03-31 09:55:27           1      0.75   4.5  1.06    0.0   
6429 2019-03-31 18:34:23           1     18.74  58.0  0.00    0.0   
6430 2019-03-23 23:14:25           1      4.14  16.0  0.00    0.0   
6431 2019-03-04 10:14:29           1      1.12   6.0  0.00    0.0   
6432 2019-03-13 19:48:02           1      3.85  15.0  3.36    0.0   

                pickup_zone                      dropoff_zone pickup_borough  \
0           Lenox Hill West               UN/Turtle Bay South      Manhattan   
1     Upper West Side South             Upper West Side South      Manhattan   
2             Alphabet City                      West Village      Manhattan   
3                 Hudson Sq                    Yorkville West      Manhattan   
4              Midtown East                    Yorkville West      Manhattan   
...                     ...                               ...            ...   
6428      East Harlem North              Central Harlem North      Manhattan   
6429                Jamaica  East Concourse/Concourse Village         Queens   
6430    Crown Heights North                    Bushwick North       Brooklyn   
6431          East New York      East Flatbush/Remsen Village       Brooklyn   
6432            Boerum Hill                   Windsor Terrace       Brooklyn   

     dropoff_borough  
0          Manhattan  
1          Manhattan  
2          Manhattan  
3          Manhattan  
4          Manhattan  
...              ...  
6428       Manhattan  
6429           Bronx  
6430        Brooklyn  
6431        Brooklyn  
6432        Brooklyn  

[6433 rows x 10 columns]

In [21]:
df.drop([2,3,6430,6432],axis=0,inplace=True)

In [22]:
df

dropoff  passengers  distance  fare   tip  tolls  \
0    2019-03-23 20:27:24           1      1.60   7.0  2.15    0.0   
1    2019-03-04 16:19:00           1      0.79   5.0  0.00    0.0   
4    2019-03-30 13:37:14           3      2.16   9.0  1.10    0.0   
5    2019-03-11 10:47:31           1      0.49   7.5  2.16    0.0   
6    2019-03-26 21:17:29           1      3.65  13.0  2.00    0.0   
...                  ...         ...       ...   ...   ...    ...   
6426 2019-03-28 08:07:46           1      0.71   4.5  0.50    0.0   
6427 2019-03-23 18:49:12           1      7.07  20.0  0.00    0.0   
6428 2019-03-31 09:55:27           1      0.75   4.5  1.06    0.0   
6429 2019-03-31 18:34:23           1     18.74  58.0  0.00    0.0   
6431 2019-03-04 10:14:29           1      1.12   6.0  0.00    0.0   

                    pickup_zone                      dropoff_zone  \
0               Lenox Hill West               UN/Turtle Bay South   
1         Upper West Side South             Upper West Side South   
4                  Midtown East                    Yorkville West   
5     Times Sq/Theatre District                      Midtown East   
6             Battery Park City           Two Bridges/Seward Park   
...                         ...                               ...   
6426               Central Park             Upper West Side North   
6427                Parkchester                 East Harlem South   
6428          East Harlem North              Central Harlem North   
6429                    Jamaica  East Concourse/Concourse Village   
6431              East New York      East Flatbush/Remsen Village   

     pickup_borough dropoff_borough  
0         Manhattan       Manhattan  
1         Manhattan       Manhattan  
4         Manhattan       Manhattan  
5         Manhattan       Manhattan  
6         Manhattan       Manhattan  
...             ...             ...  
6426      Manhattan       Manhattan  
6427          Bronx       Manhattan  
6428      Manhattan       Manhattan  
6429         Queens           Bronx  
6431       Brooklyn        Brooklyn  

[6429 rows x 10 columns]

In [23]:
np.random.randint(10,50,15)

array([13, 32, 13, 25, 18, 41, 35, 36, 33, 22, 49, 42, 44, 40, 20])

In [24]:
a=np.random.randint(10,50,15)

In [25]:
a>20

array([False,  True,  True,  True,  True,  True,  True, False,  True,
        True, False, False,  True, False,  True])

In [26]:
a

array([10, 43, 22, 34, 30, 35, 23, 11, 33, 36, 12, 10, 47, 12, 37])

In [27]:
a[a>20]

array([43, 22, 34, 30, 35, 23, 33, 36, 47, 37])

In [28]:
a[a<40]

array([10, 22, 34, 30, 35, 23, 11, 33, 36, 12, 10, 12, 37])

In [29]:
df.iloc[6000]

dropoff                       2019-03-30 00:18:31
passengers                                      1
distance                                     0.99
fare                                          5.5
tip                                           0.0
tolls                                         0.0
pickup_zone        Long Island City/Hunters Point
dropoff_zone              Queensbridge/Ravenswood
pickup_borough                             Queens
dropoff_borough                            Queens
Name: 6002, dtype: object

In [30]:
df=sns.load_dataset('taxis')
df

pickup             dropoff  passengers  distance  fare  \
0    2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.0   
1    2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0   
2    2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.5   
3    2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.0   
4    2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.0   
...                  ...                 ...         ...       ...   ...   
6428 2019-03-31 09:51:53 2019-03-31 09:55:27           1      0.75   4.5   
6429 2019-03-31 17:38:00 2019-03-31 18:34:23           1     18.74  58.0   
6430 2019-03-23 22:55:18 2019-03-23 23:14:25           1      4.14  16.0   
6431 2019-03-04 10:09:25 2019-03-04 10:14:29           1      1.12   6.0   
6432 2019-03-13 19:31:22 2019-03-13 19:48:02           1      3.85  15.0   

       tip  tolls  total   color      payment            pickup_zone  \
0     2.15    0.0  12.95  yellow  credit card        Lenox Hill West   
1     0.00    0.0   9.30  yellow         cash  Upper West Side South   
2     2.36    0.0  14.16  yellow  credit card          Alphabet City   
3     6.15    0.0  36.95  yellow  credit card              Hudson Sq   
4     1.10    0.0  13.40  yellow  credit card           Midtown East   
...    ...    ...    ...     ...          ...                    ...   
6428  1.06    0.0   6.36   green  credit card      East Harlem North   
6429  0.00    0.0  58.80   green  credit card                Jamaica   
6430  0.00    0.0  17.30   green         cash    Crown Heights North   
6431  0.00    0.0   6.80   green  credit card          East New York   
6432  3.36    0.0  20.16   green  credit card            Boerum Hill   

                          dropoff_zone pickup_borough dropoff_borough  
0                  UN/Turtle Bay South      Manhattan       Manhattan  
1                Upper West Side South      Manhattan       Manhattan  
2                         West Village      Manhattan       Manhattan  
3                       Yorkville West      Manhattan       Manhattan  
4                       Yorkville West      Manhattan       Manhattan  
...                                ...            ...             ...  
6428              Central Harlem North      Manhattan       Manhattan  
6429  East Concourse/Concourse Village         Queens           Bronx  
6430                    Bushwick North       Brooklyn        Brooklyn  
6431      East Flatbush/Remsen Village       Brooklyn        Brooklyn  
6432                   Windsor Terrace       Brooklyn        Brooklyn  

[6433 rows x 14 columns]

In [31]:
df[df['color']=='yellow']

pickup             dropoff  passengers  distance  fare  \
0    2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.0   
1    2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0   
2    2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.5   
3    2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.0   
4    2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.0   
...                  ...                 ...         ...       ...   ...   
5446 2019-03-11 21:19:42 2019-03-11 21:29:23           1      2.09   9.5   
5447 2019-03-20 18:09:46 2019-03-20 18:16:52           1      1.52   7.5   
5448 2019-03-09 11:08:09 2019-03-09 11:18:03           1      2.05   9.5   
5449 2019-03-22 18:12:50 2019-03-22 18:22:05           1      1.07   7.5   
5450 2019-03-07 18:02:33 2019-03-07 18:13:32           1      1.80   9.0   

       tip  tolls  total   color      payment            pickup_zone  \
0     2.15    0.0  12.95  yellow  credit card        Lenox Hill West   
1     0.00    0.0   9.30  yellow         cash  Upper West Side South   
2     2.36    0.0  14.16  yellow  credit card          Alphabet City   
3     6.15    0.0  36.95  yellow  credit card              Hudson Sq   
4     1.10    0.0  13.40  yellow  credit card           Midtown East   
...    ...    ...    ...     ...          ...                    ...   
5446  2.66    0.0  15.96  yellow  credit card      Battery Park City   
5447  2.36    0.0  14.16  yellow  credit card  Upper West Side South   
5448  2.56    0.0  15.36  yellow  credit card        Lenox Hill West   
5449  2.36    0.0  14.16  yellow  credit card           West Village   
5450  1.33    0.0  14.63  yellow  credit card    Lincoln Square East   

                      dropoff_zone pickup_borough dropoff_borough  
0              UN/Turtle Bay South      Manhattan       Manhattan  
1            Upper West Side South      Manhattan       Manhattan  
2                     West Village      Manhattan       Manhattan  
3                   Yorkville West      Manhattan       Manhattan  
4                   Yorkville West      Manhattan       Manhattan  
...                            ...            ...             ...  
5446      Financial District North      Manhattan       Manhattan  
5447         Upper East Side North      Manhattan       Manhattan  
5448         Upper West Side South      Manhattan       Manhattan  
5449  Penn Station/Madison Sq West      Manhattan       Manhattan  
5450         Upper West Side North      Manhattan       Manhattan  

[5451 rows x 14 columns]